### ISSUE TITLE
pagetitlebar.uc.js

### ISSUE THREAD

**Issue by tortious** [GrosBourrin/FIREFOX-BLUE-MOON#1]
Does this still work for you?
I used to have a different version that provided a pagetitlebar, but it acted more the way an addon does, in that it was easily movable around various toolbars, etc. 

When attempting to use yours, I cannot find it displayed anywhere (hopefully that is not just me being dim lol). 

Thanks, in advance (and really like your sense of style when it comes to customization).

**Comment by GrosBourrin** [comment]
no working anymore, js and xml files are innefective now, except with config.js but i dunno how to use them. sorry for late answer and my bad english. I have update my userChrome.css and userContent.css files

**Comment by tortious** [comment]
Hey dude, actually, The page-title.uc.js is now working again. 

[Here](https://github.com/tkhquang/userChrome.js/blob/master/titlebar_movable.uc.js) is the link

**Comment by GrosBourrin** [comment]
```
/* Shows window title in menubar */
/* Enable menubar for correct behavior */
@-moz-document url(chrome://browser/content/browser.xhtml) {
	:root:not([sizemode="fullscreen"])>head {
		display: block !important;
		position: fixed !important;
		right: 140px;
		/* Space for window controls */
		width: calc(100vw - 830px) !important;
		/* Window width - window control width - menuitem (English) width */
		text-align: left !important;
	}
	head>* {
		display: none;
	}
	head>title {
		display: -moz-box !important;
		padding-top: 7px !important;
		margin-top: 6px !important;
		max-width: 60vw !important;
		overflow-x: -moz-hidden-unscrollable !important;
		text-overflow: ellipsis !important;
		-moz-box-pack: right;
		font-family: Fira Sans !important;
		font-size: 14px !important;
		color: dodgerblue !important;
	}
	@media (-moz-os-version:windows-win10) {
		:root[sizemode="maximized"]>head>title {
			padding-top: 9px !important;
		}
	}
}

```
